App_Login/urls.py
from django.urls import path
from App_Login import views

app_name ="App_Login"

urlpatterns = [
    path('signup/', views.sign_up,name ='sign_up'),
    path('login/', views.login_page, name = 'login'),
    path('index/', views.index, name = 'index'),
    path('logout/', views.logout_user, name = 'logout'),
    
]

App_post/urls.py
from django.urls import path
from App_post import views

app_name = "App_post"

urlpatterns = [
    path('new/', views.new, name='new'),
    path("input/", views.input_page, name="input_page"),
    path("results/<str:prediction>/", views.results_page, name="results_page"),
    path('results/', views.results_page, name='results_page'),
    path("input/", views.input_page, name="input_page"),
    path("results/<str:prediction>/", views.results_page, name="results_page"),
    path("pdf/<str:prediction>/", views.download_pdf, name="download_pdf"),
    path('generate-pdf/', views.render_to_pdf, name='generate_pdf'),
    path("data/pdf/<str:prediction>/", views.download_pdf, name="download_pdf"),
    path('download/<str:prediction>/', views.down_pdf, name='down_pdf'),


    
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
    path('<int:blog_id>/', views.detail, name='detail'),
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf import settings
from django.conf.urls.static import static
# Only import views you need directly
from portfolio import views as portfolio_views
from App_post import views as app_post_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', portfolio_views.home, name='home'),
    path('blog/', include('blog.urls')),
    path('accounts/',include('App_Login.urls')),
    path('data/',include('App_post.urls')),
    path('new/', app_post_views.new, name='new'),
    path("input/", app_post_views.input_page, name="input_page"),
    path("results/<str:prediction>/", app_post_views.results_page, name="results_page"),
    path('data/', include('App_post.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/models.py
from django.db import models

class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

portfolio/views.py
from django.shortcuts import render
from .models import Project

def home(request):
    projects = Project.objects.all()
    return render(request, 'portfolio/home.html', {'projects':projects})

templates/portfolio/home.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

  <link rel="stylesheet" href="{% static "portfolio/custom.css" %}">
  <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">
  <link rel="icon" type="image/png" href="{% static "portfolio/new.png" %}">

  <style>
       .card-title {
      font-size: 2.5rem; /* Larger heading */
    }
    .card-text {
      font-size: 1.3rem; /* Larger paragraph text */
    }
    .card {
      margin-bottom: 10rem;
      border: none !important; /* Remove unwanted borders */
    }
    body {
      font-family: 'Lato', sans-serif;
    }

    .navbar {
      background-color: #fff;
      padding: 1rem 1.5rem;
      box-shadow: 0 4px 8px rgba(0,0,0,0.05);
    }

    .navbar-brand span {
      font-size: 24px;
      font-weight: bold;
      margin-left: 8px;
    }

    .nav-link {
      font-size: 18px;
      margin-right: 15px;
      color: #333 !important;
      transition: color 0.3s;
    }

    .nav-link:hover {
      color: #0066cc !important;
    }

    .btn-primary {
      font-size: 18px;
      padding: 6px 16px;
      background-color: #0066cc;
      border: none;
    }

    .btn-primary:hover {
      background-color: #f5a391;
    }

    .container {
      margin-top: 20px;
    }
  </style>

  <title>Lung Cancer</title>
</head>

<body>

  <!-- NAVBAR -->
  <nav id="topNav" class="navbar navbar-expand-md navbar-light" style="width: 100%;">
    <div class="container-fluid px-4">
      <a class="navbar-brand d-flex align-items-center" href="{% url 'home' %}">
        <img src="{% static 'portfolio/new.png' %}" width="35" height="35" alt="Logo">
        <span>Lung Cancer</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav">
        <span class="navbar-toggler-icon"></span>
      </button>
  
      <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
        <ul class="navbar-nav align-items-center">
          
          <li class="nav-item">
            <a role="button" href="{% url 'App_Login:login' %}" class="btn btn-primary" style="padding: 12px 24px; font-size: 1.25rem;">Log In</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  

  <!-- PAGE CONTENT -->
  <div class="container">

    <div class="row justify-content-center my-3">
      {% comment %} <div class="text-center">
    <img src="{% static 'portfolio/L.jpg' %}" class="img-fluid" style="width: 1500px;" alt="Lung Image">

</div> {% endcomment %}
   <div style="width: 1920px; height: 1080px; margin: 0 auto; display: flex; justify-content: center; align-items: center;">
    <img src="{% static 'portfolio/A.jpg' %}" 
         alt="Lung Image" 
         style="width: 260%; height: 205%; object-fit: contain;">
         <!-- Text over image -->
    <div style="
        position: absolute;
        bottom: -280px;
        left: 40%;
        background-color: rgba(255, 255, 255, 0.7);
        padding: 10px 20px;
        border-radius: 8px;
        font-size: 42px;
        font-weight: bold;
        color: #000;">
         Your Lungs, Your Life — Screen Early 
    </div>
</div>

      </div>
    </div>

 

    <hr>

<div style="border: 0px dashed #ccc; width: 300px; height: 200px; margin: 20px auto;"></div>

<div class="container-fluid d-flex justify-content-center mt-5">
  <div class="w-100" style="max-width: 75%;">

    <!-- Card 1 -->
    <div class="card shadow-sm" style="height: 350px; margin-bottom: 20rem;">
      <div class="row g-0 h-100">
        <div class="col-md-4">
          <img src="{% static 'portfolio/Lung.jpg' %}" class="img-fluid h-100 w-100" style="object-fit: cover;" alt="Lung Cancer">
        </div>
        <div class="col-md-8 d-flex align-items-center">
          <div class="card-body text-start">
            <h3 class="card-title fw-bold mb-3 fs-3">🔬 What is Lung Cancer?</h3>
            <p class="card-text fs-4" style="font-size: 28px;">
              Lung cancer is a type of cancer that begins in the lungs, often triggered by uncontrolled cell growth in lung tissues. It is typically categorized into two main types: small cell lung cancer (SCLC) and non-small cell lung cancer (NSCLC), with NSCLC being more common. The disease is often caused by long-term exposure to harmful substances such as tobacco smoke, pollutants, or radiation. In its early stages, lung cancer may not show any symptoms, making timely detection crucial. Our platform is dedicated to spreading awareness and offering preliminary digital screening using advanced machine learning techniques.
            </p>
          </div>
        </div>
      </div>
    </div>

    <!-- Card 2 -->
    <div class="card shadow-sm" style="height: 350px; margin-bottom: 20rem;">
      <div class="row g-0 h-100">
        <div class="col-md-4">
          <img src="{% static 'portfolio/2.jpg' %}" class="img-fluid h-100 w-100" style="object-fit: cover;" alt="Recognizing Symptoms">
        </div>
        <div class="col-md-8 d-flex align-items-center">
          <div class="card-body text-start">
            <h3 class="card-title fw-bold mb-3 fs-3">⚠️ Recognizing the Symptoms Early</h3>
            <p class="card-text fs-4" style="font-size: 28px;">
              Many people with early-stage lung cancer experience little or no symptoms, which is why it often goes undetected until it reaches a more advanced stage. However, there are warning signs you should not ignore. These include a persistent cough that doesn’t go away, coughing up blood, wheezing, chest pain that worsens with deep breathing or coughing, shortness of breath, hoarseness, fatigue, and unexplained weight loss. While these symptoms can be related to other illnesses, it is always best to get them evaluated by a healthcare provider. Understanding these symptoms is the first step in taking charge of your lung health.
            </p>
          </div>
        </div>
      </div>
    </div>

    <!-- Card 3 -->
    <div class="card shadow-sm" style="height: 350px; margin-bottom: 20rem;">
      <div class="row g-0 h-100">
        <div class="col-md-4">
          <img src="{% static 'portfolio/3.jpg' %}" class="img-fluid h-100 w-100" style="object-fit: cover;" alt="AI Tool">
        </div>
        <div class="col-md-8 d-flex align-items-center">
          <div class="card-body text-start">
            <h3 class="card-title fw-bold mb-3 fs-3">🧠 Use Our AI-Powered Tool to Check Your Risk</h3>
            <p class="card-text fs-4" style="font-size: 28px;">
              We have developed a smart, user-friendly tool that utilizes machine learning algorithms to predict the likelihood of lung cancer based on clinical and personal input data. This system is designed to assist in early detection by analyzing factors like age, smoking history, respiratory symptoms, and other health indicators. To get started, click the button below to proceed to our prediction page. You’ll be asked to fill in a simple form, and the system will provide an instant preliminary assessment. While this tool does not replace professional medical diagnosis, it serves as a helpful guide to encourage timely consultation with a doctor.
            </p>
            <a href="{% url 'App_Login:login'  %}" class="btn text-white shadow-sm px-5 py-3"
           style="background: linear-gradient(to right, #0066cc, #00b4d8); font-size: 32px; border-radius: 12px;">Check Your Risk</a>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>




  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
</body>

</html>

templates/portfolio/index.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

  <link rel="stylesheet" href="{% static "portfolio/custom.css" %}">
  <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">
  <link rel="icon" type="image/png" href="{% static "portfolio/new.png" %}">

  <style>
       .card-title {
      font-size: 2.5rem; /* Larger heading */
    }
    .card-text {
      font-size: 1.3rem; /* Larger paragraph text */
    }
    .card {
      margin-bottom: 10rem;
      border: none !important; /* Remove unwanted borders */
    }
    body {
      font-family: 'Lato', sans-serif;
    }

    .navbar {
      background-color: #fff;
      padding: 1rem 1.5rem;
      box-shadow: 0 4px 8px rgba(0,0,0,0.05);
    }

    .navbar-brand span {
      font-size: 24px;
      font-weight: bold;
      margin-left: 8px;
    }

    .nav-link {
      font-size: 18px;
      margin-right: 15px;
      color: #333 !important;
      transition: color 0.3s;
    }

    .nav-link:hover {
      color: #0066cc !important;
    }

    .btn-primary {
      font-size: 18px;
      padding: 6px 16px;
      background-color: #0066cc;
      border: none;
    }

    .btn-primary:hover {
      background-color: #f5a391;
    }

    .container {
      margin-top: 20px;
    }
  </style>

  <title>Lung Cancer</title>
</head>

<body>

  <!-- NAVBAR -->
  <nav id="topNav" class="navbar navbar-expand-md navbar-light" style="width: 100%;">
    <div class="container-fluid px-4">
      <a class="navbar-brand d-flex align-items-center" href="{% url 'home' %}">
        <img src="{% static 'portfolio/new.png' %}" width="35" height="35" alt="Logo">
        <span>Lung Cancer</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav">
        <span class="navbar-toggler-icon"></span>
      </button>
  
      <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
        <ul class="navbar-nav align-items-center">
          
          <li class="nav-item">
            {% comment %} <a href="{% url 'App_Login:logout' %}" class="btn btn-logout" >Log Out</a> {% endcomment %}
             <a href="{% url 'App_Login:logout' %}" class="btn text-white px-4 py-2"
   style="background: linear-gradient(to right, #ff4e50, #f9d423); border-radius: 8px; font-weight: 500; font-size: 20px;">
   Log Out
</a>

          </li>
        </ul>
      </div>
    </div>
  </nav>
  

  <!-- PAGE CONTENT -->
  <div class="container">

    <div class="row justify-content-center my-3">
      {% comment %} <div class="text-center">
    <img src="{% static 'portfolio/L.jpg' %}" class="img-fluid" style="width: 1500px;" alt="Lung Image">

</div> {% endcomment %}
   <div style="width: 1920px; height: 1080px; margin: 0 auto; display: flex; justify-content: center; align-items: center;">
    <img src="{% static 'portfolio/A.jpg' %}" 
         alt="Lung Image" 
         style="width: 260%; height: 205%; object-fit: contain;">
         <!-- Text over image -->
     <div style="
        position: absolute;
        bottom: 100px;
        left: 40%;
        background-color: rgba(255, 255, 255, 0.7);
        padding: 10px 20px;
        border-radius: 8px;
        font-size: 42px;
        font-weight: bold;
        color: #000;">
         Your Lungs, Your Life — Screen Early 
    </div>
</div>

      </div>
    </div>

 

    <hr>
    
<div style="border: 0px dashed #ccc; width: 300px; height: 200px; margin: 20px auto;"></div>

<div class="container-fluid d-flex justify-content-center mt-5">
  <div class="w-100" style="max-width: 75%;">

    <!-- Card 1 -->
    <div class="card shadow-sm" style="height: 350px; margin-bottom: 20rem;">
      <div class="row g-0 h-100">
        <div class="col-md-4">
          <img src="{% static 'portfolio/Lung.jpg' %}" class="img-fluid h-100 w-100" style="object-fit: cover;" alt="Lung Cancer">
        </div>
        <div class="col-md-8 d-flex align-items-center">
          <div class="card-body text-start">
            <h3 class="card-title fw-bold mb-3 fs-3">🔬 What is Lung Cancer?</h3>
            <p class="card-text fs-4" style="font-size: 28px;">
              Lung cancer is a type of cancer that begins in the lungs, often triggered by uncontrolled cell growth in lung tissues. It is typically categorized into two main types: small cell lung cancer (SCLC) and non-small cell lung cancer (NSCLC), with NSCLC being more common. The disease is often caused by long-term exposure to harmful substances such as tobacco smoke, pollutants, or radiation. In its early stages, lung cancer may not show any symptoms, making timely detection crucial. Our platform is dedicated to spreading awareness and offering preliminary digital screening using advanced machine learning techniques.
            </p>
          </div>
        </div>
      </div>
    </div>

    <!-- Card 2 -->
    <div class="card shadow-sm" style="height: 350px; margin-bottom: 20rem;">
      <div class="row g-0 h-100">
        <div class="col-md-4">
          <img src="{% static 'portfolio/2.jpg' %}" class="img-fluid h-100 w-100" style="object-fit: cover;" alt="Recognizing Symptoms">
        </div>
        <div class="col-md-8 d-flex align-items-center">
          <div class="card-body text-start">
            <h3 class="card-title fw-bold mb-3 fs-3">⚠️ Recognizing the Symptoms Early</h3>
            <p class="card-text fs-4" style="font-size: 28px;">
              Many people with early-stage lung cancer experience little or no symptoms, which is why it often goes undetected until it reaches a more advanced stage. However, there are warning signs you should not ignore. These include a persistent cough that doesn’t go away, coughing up blood, wheezing, chest pain that worsens with deep breathing or coughing, shortness of breath, hoarseness, fatigue, and unexplained weight loss. While these symptoms can be related to other illnesses, it is always best to get them evaluated by a healthcare provider. Understanding these symptoms is the first step in taking charge of your lung health.
            </p>
          </div>
        </div>
      </div>
    </div>

    <!-- Card 3 -->
    <div class="card shadow-sm" style="height: 350px; margin-bottom: 20rem;">
      <div class="row g-0 h-100">
        <div class="col-md-4">
          <img src="{% static 'portfolio/3.jpg' %}" class="img-fluid h-100 w-100" style="object-fit: cover;" alt="AI Tool">
        </div>
        <div class="col-md-8 d-flex align-items-center">
          <div class="card-body text-start">
            <h3 class="card-title fw-bold mb-3 fs-3">🧠 Use Our AI-Powered Tool to Check Your Risk</h3>
            <p class="card-text fs-4" style="font-size: 28px;">
              We have developed a smart, user-friendly tool that utilizes machine learning algorithms to predict the likelihood of lung cancer based on clinical and personal input data. This system is designed to assist in early detection by analyzing factors like age, smoking history, respiratory symptoms, and other health indicators. To get started, click the button below to proceed to our prediction page. You’ll be asked to fill in a simple form, and the system will provide an instant preliminary assessment. While this tool does not replace professional medical diagnosis, it serves as a helpful guide to encourage timely consultation with a doctor.
            </p>
            <a href="{% url 'App_post:input_page' %}" class="btn text-white shadow-sm px-5 py-3"
           style="background: linear-gradient(to right, #0066cc, #00b4d8); font-size: 32px; border-radius: 12px;">Check Your Risk</a>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>




  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
</body>

</html>

templates/portfolio/pdf_template.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        body { font-family: Arial, sans-serif; padding: 40px; }
        .title { font-size: 28px; color: #004b8d; margin-bottom: 20px; }
        .result-box {
            border-left: 6px solid #00b4d8;
            background: #f2faff;
            padding: 20px;
            font-size: 20px;
        }
        .prediction {
            font-weight: bold;
            font-size: 24px;
            color: {% if prediction == "yes" %} red {% else %} green {% endif %};
        }
    </style>
</head>
<body>
    <div class="title">🩺 Lung Cancer Prediction Report</div>
    <div class="result-box">
        <p>Prediction:</p>
        <p class="prediction">
            {% if prediction == "yes" %}
                Lung Cancer Detected
            {% else %}
                No Lung Cancer
            {% endif %}
        </p>
    </div>
</body>
</html>

templates/portfolio/second_home.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

  <link rel="stylesheet" href="{% static "portfolio/custom.css" %}">
  <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">
  <link rel="icon" type="image/png" href="{% static "portfolio/Logo.png" %}">

  <style>
       .card-title {
      font-size: 2.5rem; /* Larger heading */
    }
    .card-text {
      font-size: 1.3rem; /* Larger paragraph text */
    }
    .card {
      margin-bottom: 10rem;
      border: none !important; /* Remove unwanted borders */
    }
    body {
      font-family: 'Lato', sans-serif;
    }

    .navbar {
      background-color: #fff;
      padding: 1rem 1.5rem;
      box-shadow: 0 4px 8px rgba(0,0,0,0.05);
    }

    .navbar-brand span {
      font-size: 24px;
      font-weight: bold;
      margin-left: 8px;
    }

    .nav-link {
      font-size: 18px;
      margin-right: 15px;
      color: #333 !important;
      transition: color 0.3s;
    }

    .nav-link:hover {
      color: #0066cc !important;
    }

    .btn-primary {
      font-size: 18px;
      padding: 6px 16px;
      background-color: #0066cc;
      border: none;
    }

    .btn-primary:hover {
      background-color: #f5a391;
    }

    .container {
      margin-top: 20px;
    }
  </style>

  <title>Lung Cancer</title>
</head>

<body>

  <!-- NAVBAR -->
  <nav id="topNav" class="navbar navbar-expand-md navbar-light" style="width: 102%;">
    <div class="container-fluid px-4">
      <a class="navbar-brand d-flex align-items-center" href="{% url 'home' %}">
        <img src="{% static 'portfolio/Logo.png' %}" width="35" height="35" alt="Logo">
        <span>Lung Cancer</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav">
        <span class="navbar-toggler-icon"></span>
      </button>
  
      <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
        <ul class="navbar-nav align-items-center">
          <li class="nav-item">
            <a class="nav-link" href="{% static 'portfolio/resume.pdf' %}">Project Setup Instructions</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'App_Login:logout' %}" class="btn btn-logout">Log Out</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  

  <!-- PAGE CONTENT -->
  <div class="container">

    <div class="row justify-content-center my-3">
      {% comment %} <div class="text-center">
    <img src="{% static 'portfolio/L.jpg' %}" class="img-fluid" style="width: 1500px;" alt="Lung Image">

</div> {% endcomment %}
   <div style="width: 1920px; height: 1080px; margin: 0 auto; display: flex; justify-content: center; align-items: center;">
    <img src="{% static 'portfolio/A.jpg' %}" 
         alt="Lung Image" 
         style="width: 205%; height: 205%; object-fit: contain;">
         <!-- Text over image -->
    <div style="
        position: absolute;
        bottom: -130px;
        left: 35%;
        background-color: rgba(255, 255, 255, 0.7);
        padding: 10px 20px;
        border-radius: 8px;
        font-size: 36px;
        font-weight: bold;
        color: #000;">
        Your Lungs, Your Life — Screen Early
    </div>
</div>

      </div>
    </div>

 

    <hr>
<div class="container-fluid d-flex justify-content-center mt-5">
  <div class="w-100" style="max-width: 75%;">

    <!-- Card 1 -->
    <div class="card shadow-sm" style="height: 350px; margin-bottom: 20rem;">
      <div class="row g-0 h-100">
        <div class="col-md-4">
          <img src="{% static 'portfolio/Lung.jpg' %}" class="img-fluid h-100 w-100" style="object-fit: cover;" alt="Lung Cancer">
        </div>
        <div class="col-md-8 d-flex align-items-center">
          <div class="card-body text-start">
            <h3 class="card-title fw-bold mb-3 fs-3">🔬 What is Lung Cancer?</h3>
            <p class="card-text fs-4" style="font-size: 28px;">
              Lung cancer is a type of cancer that begins in the lungs, often triggered by uncontrolled cell growth in lung tissues. It is typically categorized into two main types: small cell lung cancer (SCLC) and non-small cell lung cancer (NSCLC), with NSCLC being more common. The disease is often caused by long-term exposure to harmful substances such as tobacco smoke, pollutants, or radiation. In its early stages, lung cancer may not show any symptoms, making timely detection crucial. Our platform is dedicated to spreading awareness and offering preliminary digital screening using advanced machine learning techniques.
            </p>
          </div>
        </div>
      </div>
    </div>

    <!-- Card 2 -->
    <div class="card shadow-sm" style="height: 350px; margin-bottom: 20rem;">
      <div class="row g-0 h-100">
        <div class="col-md-4">
          <img src="{% static 'portfolio/2.jpg' %}" class="img-fluid h-100 w-100" style="object-fit: cover;" alt="Recognizing Symptoms">
        </div>
        <div class="col-md-8 d-flex align-items-center">
          <div class="card-body text-start">
            <h3 class="card-title fw-bold mb-3 fs-3">⚠️ Recognizing the Symptoms Early</h3>
            <p class="card-text fs-4" style="font-size: 28px;">
              Many people with early-stage lung cancer experience little or no symptoms, which is why it often goes undetected until it reaches a more advanced stage. However, there are warning signs you should not ignore. These include a persistent cough that doesn’t go away, coughing up blood, wheezing, chest pain that worsens with deep breathing or coughing, shortness of breath, hoarseness, fatigue, and unexplained weight loss. While these symptoms can be related to other illnesses, it is always best to get them evaluated by a healthcare provider. Understanding these symptoms is the first step in taking charge of your lung health.
            </p>
          </div>
        </div>
      </div>
    </div>

    <!-- Card 3 -->
    <div class="card shadow-sm" style="height: 350px; margin-bottom: 20rem;">
      <div class="row g-0 h-100">
        <div class="col-md-4">
          <img src="{% static 'portfolio/3.jpg' %}" class="img-fluid h-100 w-100" style="object-fit: cover;" alt="AI Tool">
        </div>
        <div class="col-md-8 d-flex align-items-center">
          <div class="card-body text-start">
            <h3 class="card-title fw-bold mb-3 fs-3">🧠 Use Our AI-Powered Tool to Check Your Risk</h3>
            <p class="card-text fs-4" style="font-size: 28px;">
              We have developed a smart, user-friendly tool that utilizes machine learning algorithms to predict the likelihood of lung cancer based on clinical and personal input data. This system is designed to assist in early detection by analyzing factors like age, smoking history, respiratory symptoms, and other health indicators. To get started, click the button below to proceed to our prediction page. You’ll be asked to fill in a simple form, and the system will provide an instant preliminary assessment. While this tool does not replace professional medical diagnosis, it serves as a helpful guide to encourage timely consultation with a doctor.
            </p>
            <a href="{% url 'App_post:input_page' %}" class="btn text-white shadow-sm px-5 py-3"
           style="background: linear-gradient(to right, #0066cc, #00b4d8); font-size: 32px; border-radius: 12px;">Check Your Risk</a>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>




  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
</body>

</html>