App_Login/urls.py
from django.urls import path
from App_Login import views

app_name ="App_Login"

urlpatterns = [
    path('signup/', views.sign_up,name ='sign_up'),
    path('login/', views.login_page, name = 'login'),
    path('index/', views.index, name = 'index'),
    path('logout/', views.logout_user, name = 'logout'),
    
]

App_post/urls.py
from django.urls import path
from App_post import views

app_name = "App_post"

urlpatterns = [
    path('new/', views.new, name='new'),
    path("input/", views.input_page, name="input_page"),
    path("results/<str:prediction>/", views.results_page, name="results_page"),
    path('results/', views.results_page, name='results_page'),
    path("input/", views.input_page, name="input_page"),
    path("results/<str:prediction>/", views.results_page, name="results_page"),
    path("pdf/<str:prediction>/", views.download_pdf, name="download_pdf"),
    path('generate-pdf/', views.render_to_pdf, name='generate_pdf'),
    path("data/pdf/<str:prediction>/", views.download_pdf, name="download_pdf"),
    path('download/<str:prediction>/', views.down_pdf, name='down_pdf'),


    
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
    path('<int:blog_id>/', views.detail, name='detail'),
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf import settings
from django.conf.urls.static import static
# Only import views you need directly
from portfolio import views as portfolio_views
from App_post import views as app_post_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', portfolio_views.home, name='home'),
    path('blog/', include('blog.urls')),
    path('accounts/',include('App_Login.urls')),
    path('data/',include('App_post.urls')),
    path('new/', app_post_views.new, name='new'),
    path("input/", app_post_views.input_page, name="input_page"),
    path("results/<str:prediction>/", app_post_views.results_page, name="results_page"),
    path('data/', include('App_post.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_post/models.py
# from django.db import models
# from django.db import models
# from django.contrib.auth.models import User
# # Create your models here.

# # class PatientData(models.Model):
# #     id = models.AutoField(primary_key=True)
# #     radius_mean = models.FloatField()
# #     texture_mean = models.FloatField()
# #     perimeter_mean = models.FloatField()
# #     area_mean = models.FloatField()
# #     smoothness_mean = models.FloatField()
# #     compactness_mean = models.FloatField()
# #     concavity_mean = models.FloatField()
# #     concave_points_mean = models.FloatField()
# #     symmetry_mean = models.FloatField()
# #     fractal_dimension_mean = models.FloatField()
# #     radius_se = models.FloatField()
# #     texture_se = models.FloatField()
# #     perimeter_se = models.FloatField()
# #     area_se = models.FloatField()
# #     smoothness_se = models.FloatField()
# #     compactness_se = models.FloatField()
# #     concavity_se = models.FloatField()
# #     concave_points_se = models.FloatField()
# #     symmetry_se = models.FloatField()
# #     fractal_dimension_se = models.FloatField()
# #     radius_worst = models.FloatField()
# #     texture_worst = models.FloatField()
# #     perimeter_worst = models.FloatField()
# #     area_worst = models.FloatField()
# #     smoothness_worst = models.FloatField()
# #     compactness_worst = models.FloatField()
# #     concavity_worst = models.FloatField()
# #     concave_points_worst = models.FloatField()
# #     symmetry_worst = models.FloatField()
# #     fractal_dimension_worst = models.FloatField()
  
# class PatientData(models.Model):
#     id = models.AutoField(primary_key=True)
#     radius_mean = models.FloatField(null=True, blank=True)
#     texture_mean = models.FloatField(null=True, blank=True)
#     perimeter_mean = models.FloatField(null=True, blank=True)
#     area_mean = models.FloatField(null=True, blank=True)
#     smoothness_mean = models.FloatField(null=True, blank=True)
#     compactness_mean = models.FloatField(null=True, blank=True)
#     concavity_mean = models.FloatField(null=True, blank=True)
#     concave_points_mean = models.FloatField(null=True, blank=True)
#     symmetry_mean = models.FloatField(null=True, blank=True)
#     fractal_dimension_mean = models.FloatField(null=True, blank=True)
#     radius_se = models.FloatField(null=True, blank=True)
#     texture_se = models.FloatField(null=True, blank=True)
#     perimeter_se = models.FloatField(null=True, blank=True)
#     area_se = models.FloatField(null=True, blank=True)
#     smoothness_se = models.FloatField(null=True, blank=True)
#     compactness_se = models.FloatField(null=True, blank=True)
#     concavity_se = models.FloatField(null=True, blank=True)
#     concave_points_se = models.FloatField(null=True, blank=True)
#     symmetry_se = models.FloatField(null=True, blank=True)
#     fractal_dimension_se = models.FloatField(null=True, blank=True)
#     radius_worst = models.FloatField(null=True, blank=True)
#     texture_worst = models.FloatField(null=True, blank=True)
#     perimeter_worst = models.FloatField(null=True, blank=True)
#     area_worst = models.FloatField(null=True, blank=True)
#     smoothness_worst = models.FloatField(null=True, blank=True)
#     compactness_worst = models.FloatField(null=True, blank=True)
#     concavity_worst = models.FloatField(null=True, blank=True)
#     concave_points_worst = models.FloatField(null=True, blank=True)
#     symmetry_worst = models.FloatField(null=True, blank=True)
#     fractal_dimension_worst = models.FloatField(null=True, blank=True)
    
# class Project(models.Model):
#     title = models.CharField(max_length=100)
#     description = models.CharField(max_length=250)
#     image = models.ImageField(upload_to='portfolio/images/')
#     url = models.URLField(blank=True)

#     def __str__(self):
#         return self.title

# from django.db import models

# class PatientData(models.Model):
#     GENDER_CHOICES = [
#         (0, "Male"),
#         (1, "Female"),
#     ]

#     YES_NO_CHOICES = [
#         (1, "No"),
#         (2, "Yes"),
#     ]

#     id = models.AutoField(primary_key=True)
#     gender = models.IntegerField(choices=GENDER_CHOICES)
#     age = models.IntegerField()
#     smoking = models.IntegerField(choices=YES_NO_CHOICES)
#     yellow_fingers = models.IntegerField(choices=YES_NO_CHOICES)
#     anxiety = models.IntegerField(choices=YES_NO_CHOICES)
#     peer_pressure = models.IntegerField(choices=YES_NO_CHOICES)
#     chronic_disease = models.IntegerField(choices=YES_NO_CHOICES)
#     fatigue = models.IntegerField(choices=YES_NO_CHOICES)
#     allergy = models.IntegerField(choices=YES_NO_CHOICES)
#     wheezing = models.IntegerField(choices=YES_NO_CHOICES)
#     alcohol_consuming = models.IntegerField(choices=YES_NO_CHOICES)
#     coughing = models.IntegerField(choices=YES_NO_CHOICES)
#     shortness_of_breath = models.IntegerField(choices=YES_NO_CHOICES)
#     swallowing_difficulty = models.IntegerField(choices=YES_NO_CHOICES)
#     chest_pain = models.IntegerField(choices=YES_NO_CHOICES)

#     def __str__(self):
#         return f"Patient {self.id} - Age {self.age}"

# class Project(models.Model):
#     title = models.CharField(max_length=100)
#     description = models.CharField(max_length=250)
#     image = models.ImageField(upload_to='portfolio/images/')
#     url = models.URLField(blank=True)

#     def __str__(self):
#         return self.title
from django.db import models

# class PatientData(models.Model):
#     GENDER_CHOICES = [
#         (0, "Male"),
#         (1, "Female"),
#     ]

#     YES_NO_CHOICES = [
#         (1, "No"),
#         (2, "Yes"),
#     ]

#     id = models.AutoField(primary_key=True)
#     gender = models.IntegerField(choices=GENDER_CHOICES, default=1)
#     age = models.IntegerField(default=30)

#     smoking = models.IntegerField(choices=YES_NO_CHOICES, default=1)
#     yellow_fingers = models.IntegerField(choices=YES_NO_CHOICES, default=1)
#     anxiety = models.IntegerField(choices=YES_NO_CHOICES, default=1)
#     peer_pressure = models.IntegerField(choices=YES_NO_CHOICES, default=1)
#     chronic_disease = models.IntegerField(choices=YES_NO_CHOICES, default=1)
#     fatigue = models.IntegerField(choices=YES_NO_CHOICES, default=1)
#     allergy = models.IntegerField(choices=YES_NO_CHOICES, default=1)
#     wheezing = models.IntegerField(choices=YES_NO_CHOICES, default=1)
#     alcohol_consuming = models.IntegerField(choices=YES_NO_CHOICES, default=1)
#     coughing = models.IntegerField(choices=YES_NO_CHOICES, default=1)
#     shortness_of_breath = models.IntegerField(choices=YES_NO_CHOICES, default=1)
#     swallowing_difficulty = models.IntegerField(choices=YES_NO_CHOICES, default=1)
#     chest_pain = models.IntegerField(choices=YES_NO_CHOICES, default=1)

#     def __str__(self):
#         return f"Patient {self.id} - Age {self.age}"
from django.db import models


class PatientData(models.Model):
    GENDER_CHOICES = [
        (0, "Male"),
        (1, "Female"),
    ]

    YES_NO_CHOICES = [
        (1, "No"),
        (2, "Yes"),
    ]

    id = models.AutoField(primary_key=True)
    gender = models.IntegerField(choices=GENDER_CHOICES, default=1)
    age = models.IntegerField(default=30)
    chronic_disease = models.IntegerField(choices=YES_NO_CHOICES, default=1)
    wheezing = models.IntegerField(choices=YES_NO_CHOICES, default=1)
    alcohol_consuming = models.IntegerField(choices=YES_NO_CHOICES, default=1)
    chest_pain = models.IntegerField(choices=YES_NO_CHOICES, default=1)
    smoking = models.IntegerField(choices=YES_NO_CHOICES, default=1)
    yellow_fingers = models.IntegerField(choices=YES_NO_CHOICES, default=1)
    coughing = models.IntegerField(choices=YES_NO_CHOICES, default=1)
    shortness_of_breath = models.IntegerField(choices=YES_NO_CHOICES, default=1)

    def __str__(self):
        return f"Patient {self.id} - Age {self.age}"
class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

App_post/views.py
# import os
# import numpy as np
# import joblib
# from datetime import datetime
# from django.conf import settings
# from django.http import HttpResponse, FileResponse
# from django.shortcuts import render, redirect
# from django.contrib.auth.decorators import login_required
# from django.template.loader import get_template
# from weasyprint import HTML

# from .forms import BreastCancerForm
# from .models import PatientData, Project
# from .utils import render_to_pdf

# PIPELINE_PATH = "App_post/pipeline.pkl"
# pipeline = joblib.load(PIPELINE_PATH)

# @login_required
# def input_page(request):
#     if request.method == "POST":
#         form = BreastCancerForm(request.POST)
#         if form.is_valid():
#             field_order = ['age', 'chronic_disease', 'wheezing', 'alcohol_consuming', 'chest_pain',
#                            'smoking', 'yellow_fingers', 'coughing', 'shortness_of_breath', 'gender']
#             input_dict = {field: form.cleaned_data.get(field, 1) for field in field_order}

#             request.session["input_data"] = input_dict
#             input_array = [input_dict[field] for field in field_order]
#             result = pipeline.predict([input_array])[0]
#             prediction = "Lung Cancer Detected" if result == 2 else "No Lung Cancer"

#             return redirect("App_post:results_page", prediction=prediction)
#     else:
#         form = BreastCancerForm()

#     return render(request, "App_post/input_page.html", {"form": form})

# @login_required
# def results_page(request, prediction):
#     return render(request, "App_post/results_page.html", {"prediction": prediction})

# @login_required
# def new(request):
#     projects = Project.objects.all()
#     return render(request, 'App_post/new.html', context={'title': 'Home Page', 'projects': projects})

# @login_required
# def download_pdf(request, prediction):
#     input_data = request.session.get("input_data")
#     if not input_data:
#         return HttpResponse("No input data found in session.", status=400)

#     context = {
#         "user": request.user,
#         "input_data": input_data,
#         "prediction": prediction
#     }

#     return render_to_pdf("App_post/pdf_template.html", context)

# @login_required
# def down_pdf(request, prediction):
#     input_data = request.session.get("input_data")
#     if not input_data:
#         return HttpResponse("No input data found in session.", status=400)

#     context = {
#         "user": request.user,
#         "input_data": input_data,
#         "prediction": prediction
#     }

#     template = get_template("App_post/pdf_template.html")
#     html_string = template.render(context)
#     html = HTML(string=html_string)
#     pdf_file = html.write_pdf()

#     filename = f"Lung_Cancer_Result_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
#     save_path = os.path.join(settings.MEDIA_ROOT, filename)

#     with open(save_path, "wb") as f:
#         f.write(pdf_file)

#     return FileResponse(open(save_path, "rb"), as_attachment=True, filename=filename)

# model = joblib.load("App_post/pipeline.pkl")

# @login_required
# def predict_view(request):
#     if request.method == "POST":
#         input_fields = ['chronic_disease', 'wheezing', 'alcohol_consuming', 'chest_pain',
#                         'shortness_of_breath', 'smoking', 'yellow_fingers', 'coughing', 'age', 'gender']
#         input_data = {field: int(request.POST.get(field, 1)) for field in input_fields}

#         request.session["input_data"] = input_data

#         features = np.array([[input_data[field] for field in input_fields]])
#         result = model.predict(features)[0]
#         prediction = "Lung Cancer Detected" if result == 2 else "No Lung Cancer"

#         return redirect("download_pdf", prediction=prediction)
import os
import numpy as np
import joblib
from datetime import datetime
from django.conf import settings
from django.http import HttpResponse, FileResponse
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.template.loader import get_template
from weasyprint import HTML

from .forms import BreastCancerForm
from .models import PatientData, Project
from .utils import render_to_pdf

PIPELINE_PATH = "App_post/pipeline.pkl"
pipeline = joblib.load(PIPELINE_PATH)

# These are the 5 features your model expects
MODEL_FEATURES = ['age', 'chronic_disease', 'wheezing', 'alcohol_consuming', 'chest_pain']

@login_required
def input_page(request):
    if request.method == "POST":
        form = BreastCancerForm(request.POST)
        if form.is_valid():
            all_fields = form.cleaned_data
            request.session["input_data"] = all_fields

            # Select only the 5 model features in the correct order
            model_input = [all_fields.get(field, 0) for field in ['age', 'chronic_disease', 'wheezing', 'alcohol_consuming', 'chest_pain']]
            prediction_result = pipeline.predict([model_input])[0]
            prediction = "Lung Cancer Detected" if prediction_result == 2 else "No Lung Cancer"

            return redirect("App_post:results_page", prediction=prediction)
    else:
        form = BreastCancerForm()

    return render(request, "App_post/input_page.html", {"form": form})

@login_required
def results_page(request, prediction):
    return render(request, "App_post/results_page.html", {"prediction": prediction})

@login_required
def new(request):
    projects = Project.objects.all()
    return render(request, 'App_post/new.html', context={'title': 'Home Page', 'projects': projects})

@login_required
def download_pdf(request, prediction):
    input_data = request.session.get("input_data")
    if not input_data:
        return HttpResponse("No input data found in session.", status=400)

    context = {
        "user": request.user,
        "input_data": input_data,
        "prediction": prediction
    }

    return render_to_pdf("App_post/pdf_template.html", context)

@login_required
def down_pdf(request, prediction):
    input_data = request.session.get("input_data")
    if not input_data:
        return HttpResponse("No input data found in session.", status=400)

    context = {
        "user": request.user,
        "input_data": input_data,
        "prediction": prediction
    }

    template = get_template("App_post/pdf_template.html")
    html_string = template.render(context)
    html = HTML(string=html_string)
    pdf_file = html.write_pdf()

    filename = f"Lung_Cancer_Result_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    save_path = os.path.join(settings.MEDIA_ROOT, filename)

    with open(save_path, "wb") as f:
        f.write(pdf_file)

    return FileResponse(open(save_path, "rb"), as_attachment=True, filename=filename)

templates/App_post/results_page.html
{% extends 'portfolio/navbar.html' %}
{% comment %} <!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Prediction Result</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<body style="background-color: pink; text-align: center;">
    <h1 style="color: darkred;">Breast Cancer Prediction Result</h1>
    <h2 style="color: {% if prediction == 'Malignant' %}red{% else %}green{% endif %};">
        The predicted result is: <strong>{{ prediction }}</strong>
    </h2>
    <br>
    <a href="{% url 'input_page' %}" style="padding: 10px; background: blue; color: white; text-decoration: none; border-radius: 5px;">Check Another</a>
</body>
</html> {% endcomment %}

{% comment %} 
{% load static %}

{% block title %}Prediction Result{% endblock %}

{% block content %}
<div class="container d-flex justify-content-center align-items-center" style="min-height: 100vh;">
  <div class="p-5 rounded shadow-lg text-center" style="background-color: #f6dbe1; max-width: 850px; width: 100%;">

    <!-- Title -->
    <h1 class="mb-4" style="color: #f34d83; font-size: 45px; font-weight: bold;">
      Breast Cancer Prediction Result
    </h1>

    <!-- Prediction Output -->
    <div class="p-4 rounded shadow-sm" style="background-color: white; border-left: 6px solid #f34d83;">
      <h3 class="mb-0" style="font-size: 40px; color: #f34d83;">Prediction:</h3>
      <p class="mt-2" style="font-size: 38px; font-weight: bold; color: {% if prediction == 'Malignant' %}red{% else %}green{% endif %};">
        {{ prediction }}
      </p>
    </div>

    <!-- Action Button -->
    <a href="{% url 'App_post:input_page' %}" class="btn text-white mt-4"
       style="background-color: #f34d83; font-size: 20px; padding: 12px 30px; border-radius: 8px;">
      Check Another
    </a>

  </div>
</div>
{% endblock %} {% endcomment %}
{% comment %} {% load static %}

{% block content %}
<div class="container mt-5 p-5 rounded-4 shadow-lg text-center" style="background: linear-gradient(to right, #f0f9ff, #dbefff); max-width: 1100px; font-family: 'Segoe UI', sans-serif;">

    <!-- Title -->
    <h1 class="mb-5" style="font-size: 45px; font-weight: 800; color: #004b8d;">
        🩺 Lung Cancer Prediction Result
    </h1>

    <!-- Prediction Output Box -->
    <div class="p-4 rounded-4 shadow-sm mx-auto" style="background-color: white; border-left: 6px solid #00b4d8; max-width: 600px;">
        <h3 class="mb-3" style="font-size: 35px; color: #0066cc;">Prediction:</h3>
        <p class="mb-0" style="font-size: 38px; font-weight: bold; color: {% if prediction == 'yes' %}red{% else %}green{% endif %};">
            {% if prediction == 'yes' %}
                Lung Cancer Detected
            {% else %}
                No Lung Cancer
            {% endif %}
        </p>
    </div>

    {% comment %} <!-- Action Button -->
    <div class="text-center mt-5">
        <a href="{% url 'App_post:input_page' %}" class="btn text-white shadow-sm px-5 py-3"
           style="background: linear-gradient(to right, #0066cc, #00b4d8); font-size: 29px; border-radius: 12px;">
             Check Another
        </a>
        <a href="{% url 'App_post:download_pdf' prediction=prediction %}" class="btn text-white shadow-sm px-5 py-3"
           style="background: linear-gradient(to right, #0066cc, #00b4d8); font-size: 29px; border-radius: 12px;">
    Show PDF Report
</a>
<a href="{% url 'App_post:down_pdf' prediction=prediction %}" class="btn text-white shadow-sm px-5 py-3"
           style="background: linear-gradient(to right, #0066cc, #00b4d8); font-size: 29px; border-radius: 12px;">Download PDF</a>

    </div> 
    <!-- Action Button -->
<!-- Hidden iframe to trigger file download -->
<!-- Hidden iframe to trigger file download -->
<iframe id="pdfFrame" style="display: none;"></iframe>

<!-- Action Buttons -->
<div class="text-center mt-5">

    <!-- Check Another -->
    <a href="{% url 'App_post:input_page' %}" class="btn text-white shadow-sm px-5 py-3"
       style="background: linear-gradient(to right, #0066cc, #00b4d8); font-size: 29px; border-radius: 12px;">
        Check Another
    </a>

    <!-- Show PDF Report (View in Browser) -->
    <a id="showPdfBtn" href="{% url 'App_post:download_pdf' prediction=prediction %}" target="_blank"
       class="btn text-white shadow-sm px-5 py-3"
       style="background: linear-gradient(to right, #0066cc, #00b4d8); font-size: 29px; border-radius: 12px;">
        <span id="showPdfText">Show PDF Report</span>
        <span id="showPdfSpinner" class="spinner-border spinner-border-sm ms-2 d-none" role="status" aria-hidden="true"></span>
    </a>

    <!-- Download PDF (File Download) -->
    <a id="downloadBtn" href="#" class="btn text-white shadow-sm px-5 py-3"
       style="background: linear-gradient(to right, #0066cc, #00b4d8); font-size: 29px; border-radius: 12px;">
        <span id="downloadText">Download Report</span>
        <span id="downloadSpinner" class="spinner-border spinner-border-sm ms-2 d-none" role="status" aria-hidden="true"></span>
    </a>
</div>

<!-- JavaScript to Handle Spinners -->
<script>
    // Handle PDF Download
    document.getElementById('downloadBtn').addEventListener('click', function (e) {
        e.preventDefault();

        const btn = this;
        const spinner = document.getElementById('downloadSpinner');
        const text = document.getElementById('downloadText');

        text.textContent = 'Downloading...';
        spinner.classList.remove('d-none');
        btn.classList.add('disabled');

        document.getElementById('pdfFrame').src = "{% url 'App_post:down_pdf' prediction=prediction %}";

        setTimeout(() => {
            text.textContent = 'Download PDF';
            spinner.classList.add('d-none');
            btn.classList.remove('disabled');
        }, 5000); // Adjust time if needed
    });

    // Handle Show PDF Report
    document.getElementById('showPdfBtn').addEventListener('click', function () {
        const btn = this;
        const spinner = document.getElementById('showPdfSpinner');
        const text = document.getElementById('showPdfText');

        text.textContent = 'Opening...';
        spinner.classList.remove('d-none');
        btn.classList.add('disabled');

        setTimeout(() => {
            text.textContent = 'Show PDF Report';
            spinner.classList.add('d-none');
            btn.classList.remove('disabled');
        }, 3000); // Slightly shorter delay since it's opening, not downloading
    });
</script>




</div>

<style>
    .btn:focus, .btn:active {
        box-shadow: none !important;
    }
</style>
{% endblock %} {% endcomment %}
{% load static %}

{% block content %}
<!-- Full-screen Centering Container -->
<div class="d-flex justify-content-center align-items-center" style="min-height: 100vh;">
    <!-- Outer Blue Box -->
    <div class="p-5 rounded-4 shadow-lg text-center" style="background: linear-gradient(to right, #f0f9ff, #dbefff); width: 90%; max-width: 1300px; font-family: 'Segoe UI', sans-serif;">

        <!-- Title -->
        <h1 class="mb-5" style="font-size: 50px; font-weight: 800; color: #004b8d;">
            🩺 Lung Cancer Prediction Result
        </h1>

        <!-- Inner White Box -->
        <div class="p-5 rounded-4 shadow-sm mx-auto" style="background-color: white; border-left: 8px solid #00b4d8; max-width: 750px;">
            <h3 class="mb-3" style="font-size: 40px; color: #0066cc;">Prediction:</h3>
            <p class="mb-0" style="font-size: 42px; font-weight: bold; color: {% if prediction == 'yes' %}red{% else %}green{% endif %};">
                {% if prediction == 'yes' %}
                    Lung Cancer Detected
                {% else %}
                    No Lung Cancer
                {% endif %}
            </p>
        </div>

        <!-- Buttons -->
        <!-- Buttons -->
<div class="d-flex justify-content-center align-items-center mt-5 flex-wrap" style="gap: 20px;">
    <!-- Check Another -->
    <a href="{% url 'App_post:input_page' %}" class="result-btn">
        Check Another
    </a>

    <!-- Show PDF Report -->
    <a id="showPdfBtn" href="{% url 'App_post:download_pdf' prediction=prediction %}" target="_blank" class="result-btn">
        <span id="showPdfText">Show PDF Report</span>
        <span id="showPdfSpinner" class="spinner-border spinner-border-sm ms-2 d-none" role="status" aria-hidden="true"></span>
    </a>

    <!-- Download Report -->
    <a id="downloadBtn" href="#" class="result-btn">
        <span id="downloadText">Download Report</span>
        <span id="downloadSpinner" class="spinner-border spinner-border-sm ms-2 d-none" role="status" aria-hidden="true"></span>
    </a>
</div>


    </div>
</div>

<!-- JavaScript for Buttons -->
<script>
    document.getElementById('downloadBtn').addEventListener('click', function (e) {
        e.preventDefault();
        const btn = this;
        const spinner = document.getElementById('downloadSpinner');
        const text = document.getElementById('downloadText');
        text.textContent = 'Downloading...';
        spinner.classList.remove('d-none');
        btn.classList.add('disabled');
        document.getElementById('pdfFrame').src = "{% url 'App_post:down_pdf' prediction=prediction %}";
        setTimeout(() => {
            text.textContent = 'Download Report';
            spinner.classList.add('d-none');
            btn.classList.remove('disabled');
        }, 5000);
    });

    document.getElementById('showPdfBtn').addEventListener('click', function () {
        const btn = this;
        const spinner = document.getElementById('showPdfSpinner');
        const text = document.getElementById('showPdfText');
        text.textContent = 'Opening...';
        spinner.classList.remove('d-none');
        btn.classList.add('disabled');
        setTimeout(() => {
            text.textContent = 'Show PDF Report';
            spinner.classList.add('d-none');
            btn.classList.remove('disabled');
        }, 3000);
    });
</script>

<!-- Styles -->
<style>
    .btn:focus, .btn:active {
        box-shadow: none !important;
    }

    .result-btn {
        flex: 1 1 280px;
        max-width: 280px;
        text-align: center;
        background: linear-gradient(to right, #0066cc, #00b4d8);
        font-size: 20px;
        font-weight: 500;
        color: white !important;
        border-radius: 12px;
        padding: 15px 0;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        text-decoration: none;
        transition: background 0.3s ease;
    }

    .result-btn:hover {
        background: linear-gradient(to right, #005bb5, #009ecf);
    }

    @media (max-width: 768px) {
        .result-btn {
            flex: 1 1 100%;
            max-width: 100%;
        }
    }
</style>
{% endblock %}